sudo: false
language: generic
dist: xenial
services:
  - xvfb

branches:
  only:
    - main

env:
  global:
    - CPPFLAGS=--coverage

matrix:
  fast_finish: true
  include:
    - os: linux
      env:
        - PYTHON=3.6
        - QT_VERSION=5
    - os: linux
      env:
        - PYTHON=3.7
        - QT_VERSION=5
    - os: linux
      env:
        - PYTHON=3.8
        - QT_VERSION=5

before_install:

  # Install Miniconda
  - travis_retry wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ~/anaconda
  - export PATH=~/anaconda/bin:$PATH

  # Setup environment
  - travis_retry conda update --yes conda
  - conda config --set always_yes yes

  # Display those for debug purposes
  - conda info -a
  - conda create -n travisci python=$PYTHON pip
  - source activate travisci
  - CONDA_INSTALL="conda install -q"
  - PIP_INSTALL="pip install"

  # Install enaml dependencies and include special widgets dependencies
  # We do not test vtk as it segfaults on Travis
  - $CONDA_INSTALL pyqt=$QT_VERSION ply matplotlib;
  - $CONDA_INSTALL qtpy

  # We do not test IPython nor QScintilla, because one is bugged on conda and the
  # other is not available

  # Install bytecode
  - $PIP_INSTALL bytecode

  # Install the dev version of the other nucleic projects
  - $PIP_INSTALL git+https://github.com/nucleic/cppy@main
  - $PIP_INSTALL git+https://github.com/nucleic/atom@main
  - $PIP_INSTALL git+https://github.com/nucleic/kiwi@main

  # Intall test tools (we require pytest > 3.3 to get the builtin logging
  # features)
  # Pytest-xvfb allows to run on CI (without a display with less magic)
  - $PIP_INSTALL pytest pytest-cov pytest-qt pytest-xvfb pyvirtualdisplay

  # Avoid annoying focus problems when running tests
  # See discussion in e.g. https://github.com/spyder-ide/spyder/pull/6132
  - sudo apt-get -qq update
  - sudo apt-get install -y matchbox-window-manager xterm libxkbcommon-x11-0
  - matchbox-window-manager&
  - sleep 5

install:

  # Install ecpy (check that build script is not broken
  - cd $TRAVIS_BUILD_DIR
  - python setup.py develop
  - cd ~

script:
  # Run the enaml test suite
  - cd $TRAVIS_BUILD_DIR
  - pytest tests --cov enaml --cov-report xml

after_success:
  - cd $TRAVIS_BUILD_DIR
  - bash <(curl -s https://codecov.io/bash)
